# Stage 1: Build React
FROM node:20-alpine AS build
WORKDIR /app
COPY web-server/package*.json ./
RUN npm install
COPY ./web-server .
# use the compose-specific env to have correct service addresses
RUN npm run build:compose

# Stage 2: Serveur Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY ./web-server/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]