version: '3.8'

services:
  # Base de données 
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: fimafeng
      POSTGRES_PASSWORD: postgres # TODO: À injecter/gérer avec un vault
      POSTGRES_DB: fimafengdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal_net
    deploy:
      placement:
        constraints:
          - node.labels.role == database
          - node.labels.env == ${TARGET_ENV}

  # Search
  search:
    image: ghcr.io/blooskyd/search:dev
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/fimafengdb
      SPRING_DATASOURCE_PASSWORD: postgres # TODO: À injecter/gérer avec un vault
    networks:
      - internal_net
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      update_config:
        order: start-first
      placement:
        constraints:
          - node.labels.role == search
          - node.labels.env == ${TARGET_ENV}

  # React
  web-server:
    image: ghcr.io/blooskyd/web-server:dev
    networks:
      - internal_net
    ports:
      - "80:80"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == web-server
          - node.labels.env == ${TARGET_ENV}

volumes:
  db_data:

networks:
  internal_net:
    driver: overlay 