//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

package edu.cgl.sirius.application;

import java.awt.*;
import java.awt.event.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.time.temporal.TemporalAmount;

import javax.swing.*;
import javax.swing.event.*;

import com.github.lgooddatepicker.components.CalendarPanel;
import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.DatePickerSettings;
import com.github.lgooddatepicker.components.DateTimePicker;
import com.github.lgooddatepicker.components.TimePickerSettings;
import com.github.lgooddatepicker.components.TimePickerSettings.TimeIncrement;

import edu.cgl.sirius.business.dto.Announce;
import edu.cgl.sirius.client.MainInsertAnnounce;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.zip.DataFormatException;

public class InsertView extends JPanel {
    private final int FRAME_WIDTH = 1280;
    private final int FRAME_HEIGHT = 720;

    private JButton logoButton;
    private JButton createButton;
    private JButton logOutButton;
    private JButton accountButton;
    private JTextField searchField;
    private JButton searchButton;
    private JButton activitiesButton;
    private JButton materialsButton;
    private JButton servicesButton;
    private JButton aroundMeButton;

    // Announce type
    private JLabel lbl_announce_type;
    private JRadioButton rbtn_activity;
    private JRadioButton rbtn_loan;
    private JRadioButton rbtn_service;

    // Announce datetime and recurrence
    private JLabel lbl_datetimestart;
    private JCheckBox cbtn_recurrence;
    private DateTimePicker dtpicker_panel;

    // Announce title
    private JLabel lbl_title;
    private JTextField tf_title;

    // Announces tags
    private JLabel lbl_tags;
    private JCheckBox cbtn_concert;
    private JCheckBox cbtn_choral;
    private JCheckBox cbtn_festival;
    private JCheckBox cbtn_children;
    private JCheckBox cbtn_teenagers;
    private JCheckBox cbtn_adults;
    private JCheckBox cbtn_seniors;
    private JCheckBox cbtn_couples;
    private JCheckBox cbtn_all_public;
    private JCheckBox cbtn_museum;
    private JCheckBox cbtn_painting;
    private JCheckBox cbtn_theater;
    private JCheckBox cbtn_visits;

    // Announce description
    private JTextArea tfa_description;
    private JLabel lbl_description;

    // Announce location and duration
    private JComboBox<String[]> cb_locations;
    private JComboBox<String[]> cb_durations;
    private JLabel lbl_location;
    private JLabel lbl_duration;

    // Publish btn and warning
    private JButton btn_publish;
    private JLabel lbl_annouce_warning;

    private HashMap<String, Integer> map_locationsItems;
    private HashMap<String, String> map_tagsItems;
    private HashMap<String, Double> map_durationItems;

    private ArrayList<JCheckBox> list_tags_checkBoxs;

    @SuppressWarnings({ "rawtypes", "unchecked" })
    public InsertView() {
        // construct preComponents
        final String SELECT_ITEM = "<Sélectionner>";

        final LocalDate today = LocalDate.now();

        map_locationsItems = new HashMap<>();
        map_locationsItems.put(SELECT_ITEM, 0);
        map_locationsItems.put("Théâtre", 1);
        map_locationsItems.put("Piscine", 2);
        map_locationsItems.put("Cinéma", 3);
        map_locationsItems.put("Bar St Patricks", 4);
        map_locationsItems.put("Place de la Mairie", 5);
        map_locationsItems.put("Parc du chateau", 6);
        map_locationsItems.put("Salle de fêtes", 7);
        map_locationsItems.put("Mairie", 8);

        String[] cb_locationsItems = { SELECT_ITEM, "Bar St Patricks", "Cinéma", "Mairie", "Parc du chateau", "Piscine",
                "Place de la Mairie", "Salle de fêtes", "Théâtre" };

        map_tagsItems = new HashMap<>();
        map_tagsItems.put("Concert", "1");
        map_tagsItems.put("Chorale", "2");
        map_tagsItems.put("Festival", "3");
        map_tagsItems.put("Enfants", "4");
        map_tagsItems.put("Jeunes", "5");
        map_tagsItems.put("Adultes", "6");
        map_tagsItems.put("Séniors", "7");
        map_tagsItems.put("Couples", "8");
        map_tagsItems.put("Tout public", "9");
        map_tagsItems.put("Musée", "10");
        map_tagsItems.put("Peinture", "11");
        map_tagsItems.put("Théâtre", "12");
        map_tagsItems.put("Visites", "13");

        list_tags_checkBoxs = new ArrayList<>();

        map_durationItems = new HashMap<>();
        map_durationItems.put(SELECT_ITEM, 0.0);
        map_durationItems.put("15min", 0.25);
        map_durationItems.put("30min", 0.5);
        map_durationItems.put("45min", 0.75);
        map_durationItems.put("1h00", 1.0);
        map_durationItems.put("1h30", 1.5);
        map_durationItems.put("2h00", 2.0);

        String[] cb_durationsItems = { SELECT_ITEM, "15min", "30min", "45min", "1h00", "1h30", "2h00" };

        // construct components
        logoButton = new JButton("LOGO");
        createButton = new JButton("(+) Proposer");
        logOutButton = new JButton("Deconnexion");
        accountButton = new JButton("Compte");
        searchField = new JTextField(5);
        searchButton = new JButton("Rechercher");
        activitiesButton = new JButton("Activités");
        materialsButton = new JButton("Matériels");
        servicesButton = new JButton("Services");
        aroundMeButton = new JButton("Autour de moi");

        lbl_announce_type = new JLabel("Type d'annonce :");
        rbtn_activity = new JRadioButton("Activité");
        rbtn_loan = new JRadioButton("Prêt");
        rbtn_service = new JRadioButton("Service");
        lbl_datetimestart = new JLabel("Date et heure de début :");
        cbtn_recurrence = new JCheckBox("Récurrent ?");
        lbl_title = new JLabel("Titre :");
        tf_title = new JTextField(5);
        lbl_tags = new JLabel("Tags :");
        cbtn_concert = new JCheckBox("Concert");
        cbtn_choral = new JCheckBox("Chorale");
        cbtn_festival = new JCheckBox("Festival");
        cbtn_children = new JCheckBox("Enfants");
        cbtn_teenagers = new JCheckBox("Jeunes");
        cbtn_adults = new JCheckBox("Adultes");
        cbtn_seniors = new JCheckBox("Séniors");
        cbtn_couples = new JCheckBox("Couples");
        cbtn_all_public = new JCheckBox("Tout public");
        cbtn_museum = new JCheckBox("Musée");
        cbtn_painting = new JCheckBox("Peinture");
        cbtn_theater = new JCheckBox("Théâtre");
        cbtn_visits = new JCheckBox("Visites");
        tfa_description = new JTextArea(5, 5);
        lbl_description = new JLabel("Description :");
        cb_locations = new JComboBox(cb_locationsItems);
        lbl_location = new JLabel("Emplacement :");
        lbl_duration = new JLabel("Durée :");
        cb_durations = new JComboBox(cb_durationsItems);
        btn_publish = new JButton("Publier l'annonce");
        lbl_annouce_warning = new JLabel("L'annonce sera publiée avec l'ID de la mairie");

        // manage components
        list_tags_checkBoxs.add(cbtn_concert);
        list_tags_checkBoxs.add(cbtn_choral);
        list_tags_checkBoxs.add(cbtn_festival);
        list_tags_checkBoxs.add(cbtn_children);
        list_tags_checkBoxs.add(cbtn_teenagers);
        list_tags_checkBoxs.add(cbtn_adults);
        list_tags_checkBoxs.add(cbtn_seniors);
        list_tags_checkBoxs.add(cbtn_couples);
        list_tags_checkBoxs.add(cbtn_all_public);
        list_tags_checkBoxs.add(cbtn_museum);
        list_tags_checkBoxs.add(cbtn_painting);
        list_tags_checkBoxs.add(cbtn_theater);
        list_tags_checkBoxs.add(cbtn_visits);

        // set components properties
        rbtn_activity.setSelected(true);
        rbtn_loan.setEnabled(false);
        rbtn_service.setEnabled(false);
        cbtn_recurrence.setEnabled(false);
        tfa_description.setLineWrap(true);
        cb_locations.setSelectedItem(SELECT_ITEM);
        cb_durations.setSelectedItem(SELECT_ITEM);
        tfa_description.setBorder(tf_title.getBorder());

        DatePickerSettings dateSettings = new DatePickerSettings();
        TimePickerSettings timeSettings = new TimePickerSettings();
        dateSettings.setAllowEmptyDates(false);
        dateSettings.setWeekNumbersDisplayed(true, true);
        dateSettings.setFormatForDatesCommonEra("dd/MM/yyyy");
        dateSettings.setFormatForDatesBeforeCommonEra("dd/MM/yyyy");
        timeSettings.setAllowEmptyTimes(false);
        timeSettings.use24HourClockFormat();
        timeSettings.initialTime = LocalTime.of(15, 30);
        timeSettings.generatePotentialMenuTimes(TimeIncrement.FifteenMinutes, null, null);
        dtpicker_panel = new DateTimePicker(dateSettings, timeSettings);

        dateSettings.setDateRangeLimits(today, today.plusYears(1));
        // tfa_description.setAutoscrolls(true);

        // adjust size and set layout
        setPreferredSize(new Dimension(1276, 619));
        setLayout(null);
        setSize(FRAME_WIDTH, FRAME_HEIGHT);

        // define fonctionnalities
        btn_publish.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                checkInputs();
            }
        });

        // add components
        add(logoButton);
        add(createButton);
        add(logOutButton);
        add(accountButton);
        add(searchField);
        add(searchButton);
        add(activitiesButton);
        add(materialsButton);
        add(servicesButton);
        add(aroundMeButton);
        add(lbl_announce_type);
        add(rbtn_activity);
        add(rbtn_loan);
        add(rbtn_service);
        add(lbl_datetimestart);
        add(dtpicker_panel);
        add(cbtn_recurrence);
        add(lbl_title);
        add(tf_title);
        add(lbl_tags);
        add(cbtn_concert);
        add(cbtn_choral);
        add(cbtn_festival);
        add(cbtn_children);
        add(cbtn_teenagers);
        add(cbtn_adults);
        add(cbtn_seniors);
        add(cbtn_couples);
        add(cbtn_all_public);
        add(cbtn_museum);
        add(cbtn_painting);
        add(cbtn_theater);
        add(cbtn_visits);
        add(tfa_description);
        add(lbl_description);
        add(cb_locations);
        add(lbl_location);
        add(cb_durations);
        add(lbl_duration);
        add(btn_publish);
        add(lbl_annouce_warning);

        // set component bounds (only needed by Absolute Positioning)
        logoButton.setBounds(25, 25, 125, 50);
        createButton.setBounds(175, 25, 125, 50);
        logOutButton.setBounds(1120, 25, 125, 50);
        accountButton.setBounds(970, 25, 125, 50);
        searchField.setBounds(325, 25, 495, 50);
        searchButton.setBounds(820, 25, 125, 50);
        activitiesButton.setBounds(100, 100, 250, 50);
        materialsButton.setBounds(375, 100, 250, 50);
        servicesButton.setBounds(650, 100, 250, 50);
        aroundMeButton.setBounds(925, 100, 250, 50);
        lbl_announce_type.setBounds(100, 180, 100, 25);
        rbtn_activity.setBounds(210, 180, 70, 25);
        rbtn_loan.setBounds(300, 180, 60, 25);
        rbtn_service.setBounds(370, 180, 70, 25);
        lbl_datetimestart.setBounds(480, 180, 150, 25);
        dtpicker_panel.setBounds(630, 180, 200, 25);
        cbtn_recurrence.setBounds(870, 180, 100, 25);
        lbl_title.setBounds(100, 230, 100, 25);
        tf_title.setBounds(140, 225, 1035, 35);
        lbl_tags.setBounds(100, 280, 100, 25);
        cbtn_concert.setBounds(150, 280, 100, 25);
        cbtn_choral.setBounds(250, 280, 100, 25);
        cbtn_festival.setBounds(350, 280, 100, 25);
        cbtn_children.setBounds(150, 310, 100, 25);
        cbtn_teenagers.setBounds(250, 310, 100, 25);
        cbtn_adults.setBounds(350, 310, 100, 25);
        cbtn_seniors.setBounds(450, 310, 100, 25);
        cbtn_couples.setBounds(550, 310, 100, 25);
        cbtn_all_public.setBounds(650, 310, 100, 25);
        cbtn_museum.setBounds(650, 280, 100, 25);
        cbtn_painting.setBounds(750, 280, 100, 25);
        cbtn_theater.setBounds(450, 280, 100, 25);
        cbtn_visits.setBounds(550, 280, 100, 25);
        tfa_description.setBounds(180, 350, 1000, 85);
        lbl_description.setBounds(100, 350, 100, 25);
        cb_locations.setBounds(1030, 280, 145, 25);
        lbl_location.setBounds(935, 280, 100, 25);
        cb_durations.setBounds(1030, 310, 145, 25);
        lbl_duration.setBounds(935, 310, 100, 25);
        btn_publish.setBounds(560, 460, 165, 45);
        lbl_annouce_warning.setBounds(515, 510, 260, 30);
        // enable or disable components
        this.logoButton.setEnabled(false);
        this.createButton.setEnabled(true);
        this.logOutButton.setEnabled(false);
        this.accountButton.setEnabled(false);
        this.searchField.setEnabled(false);
        this.searchButton.setEnabled(false);
        this.activitiesButton.setEnabled(true);
        this.materialsButton.setEnabled(false);
        this.servicesButton.setEnabled(false);
        this.aroundMeButton.setEnabled(true);
    }

    private void checkInputs() {
        try {
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Date date_now = new Date();
            String publication_date = dateFormat.format(date_now);
            String is_recurrent = "f";
            String price = "0.0";
            String author_id = "1";

            LocalDateTime ldt_start = dtpicker_panel.getDateTimeStrict();
            Date dstart = Date.from(ldt_start.atZone(ZoneId.systemDefault()).toInstant());
            String date_time_start = dateFormat.format(dstart);

            String status = "online";
            String title = checkTitle();
            @SuppressWarnings("unused")
            ArrayList<String> list_tags_id = checkTags();
            String description = checkDescription();
            String location_id = String.valueOf(checkLocation());

            double vduration = checkDuration();
            String duration = String.valueOf(vduration);
            vduration = vduration * 60;
            long minutes_duration = (long) vduration;

            LocalDateTime ldt_end = ldt_start.plusMinutes(minutes_duration);
            Date dend = Date.from(ldt_end.atZone(ZoneId.systemDefault()).toInstant());
            String date_time_end = dateFormat.format(dend);

            JOptionPane.showMessageDialog(this, "Donneés valides");

            new MainInsertAnnounce("INSERT_ANNOUNCE", author_id, publication_date,
                    status, "activité", title,
                    description, date_time_start, duration, date_time_end, is_recurrent, null,
                    null, price, location_id, list_tags_id);

        } catch (DataFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Saisie incorrecte", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Todo
        }

    }

    private String checkTitle() throws DataFormatException {
        String title = this.tf_title.getText();
        if (title.equals(""))
            throw new DataFormatException("Le titre n'est pas renseigné");
        if (title.length() > 100)
            throw new DataFormatException("Le titre est trop long (sup. à 100 caractères)");
        return title;
    }

    private ArrayList<String> checkTags() throws DataFormatException {
        ArrayList<String> selected_tags_id = new ArrayList<>();
        for (JCheckBox jCheckBox : list_tags_checkBoxs) {
            if (jCheckBox.isSelected()) {
                selected_tags_id.add(map_tagsItems.get(jCheckBox.getText()));
            }
        }
        if (selected_tags_id.isEmpty())
            throw new DataFormatException("Aucun tag n'a été sélectionné");
        if (selected_tags_id.size() > 5)
            throw new DataFormatException("Trop de tags ont été sélectionnés (+ de 5)");
        return selected_tags_id;

    }

    private String checkDescription() throws DataFormatException {
        String description = this.tfa_description.getText();
        if (description.length() > 1000)
            throw new DataFormatException("La description est trop longue (sup. à 1000 caractères)");
        return description;
    }

    private int checkLocation() throws DataFormatException {
        int location_id = map_locationsItems.get(cb_locations.getSelectedItem());
        if (location_id == 0)
            throw new DataFormatException("Aucun emplacement choisit");
        return location_id;
    }

    private double checkDuration() throws DataFormatException {
        double duration = map_durationItems.get(cb_durations.getSelectedItem());
        if (duration == 0.0)
            throw new DataFormatException("Aucune durée choisie");
        return duration;
    }

    public static void start(Component component) {
        JFrame frame = new JFrame("insertview");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setResizable(false);
        frame.getContentPane().add(new InsertView());
        frame.pack();
        frame.setLocationRelativeTo(component);
        frame.setVisible(true);

    }
}
