spring.application.name=fimafeng-announce-manager
application.short-name=ann-man

# Postgres DataSource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/fimafengdb
spring.datasource.username=fimafeng

# JPA/Hibernate
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.address=0.0.0.0
server.port=8080
access.allow.origin=*

# Notification Service Configuration
notification-service.url=http://notification-manager:8080
# Moderation Service Configuration
moderation-service.url=http://localhost:8084

# Log pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5p) [${application.short-name}] %clr(%36.36c{36}){cyan}%clr(:%-3L){faint}   - %m%n
spring.output.ansi.enabled=ALWAYS

# Kafka
spring.kafka.bootstrap-servers=notif-lb:9092,notif-kafka1:9092,notif-kafka2:9092
# Reduce blocking time when Kafka metadata is unavailable to avoid long request delays
spring.kafka.properties.max.block.ms=2000
spring.kafka.producer.retries=0

# Serializer Configuration for key
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Configuration du Serializer pour la valeur (conversion de l'objet Java en JSON)
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Optionnel : Désactive l'ajout du nom de la classe Java dans les headers du message
spring.kafka.producer.properties.spring.json.add.type.headers=false