#just for tac
statistics=true
job=SourceToBronze
jobVersion=0.1
date=2026-03-27 154355502
contextName=Default
jobId=_-6uQoNEnEfCGnvpoM1xAIA
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=LOCAL_PROJECT
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=